/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import Business.Organization;
import Business.Restaurant.Food;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import Business.WorkQueue.FoodWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class OrderJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private UserAccount userAccount;
    /**
     * Creates new form RequestLabTestJPanel
     */
    public OrderJPanel(JPanel userProcessContainer, UserAccount account,EcoSystem ecosystem) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.ecosystem=ecosystem;
        this.userAccount = account;
        populateRequestTable();
        initialate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        btnBool = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JComboBox1 = new javax.swing.JComboBox();
        JComboBox2 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        btnBool.setText("BookAndComment");
        btnBool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoolActionPerformed(evt);
            }
        });
        add(btnBool, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Restaurant", "Food"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 280, 100));

        JComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBox1ActionPerformed(evt);
            }
        });
        add(JComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        JComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(JComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 140, -1));
    }// </editor-fold>//GEN-END:initComponents
    public void populateRequestTable(){
          DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[2];
            row[0] = request.getReceiver();
            row[1] = request.getFood();          
            model.addRow(row);
        }
 

    }
    private void initialate(){
       // RestaurantDirectory restaurantDir = new RestaurantDirectory();
        JComboBox1.removeAllItems();
        for(Restaurant r : ecosystem.getRestaurantDirectory().getRestaurantList()){
            JComboBox1.addItem(r);
        }
    }
    
    private void populatefoodComboBox(Restaurant restaurant){
        JComboBox2.removeAllItems();
        
        for (Food food : restaurant.getFoodList()){
            JComboBox2.addItem(food);
        }
        
    }
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerAreaJPanel dwjp = (CustomerAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnBoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoolActionPerformed
        // TODO add your handling code here:
        FoodWorkRequest request = new FoodWorkRequest();
       
        //UserAccountDirectory ud = new UserAccountDirectory();
        String message = jTextField1.getText();
        String food = String.valueOf(JComboBox2.getSelectedItem());
        String re = String.valueOf(JComboBox1.getSelectedItem());
        request.setFood(food);
        request.setReceiver(ecosystem.getUserAccountDirectory().getuserAccountbyName(re));
        request.setSender(userAccount);
        request.setStatus("Order");
        request.setMessage(message);
        userAccount.getWorkQueue().getWorkRequestList().add(request);        
        
        
        populateRequestTable();
    }//GEN-LAST:event_btnBoolActionPerformed

    private void JComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBox1ActionPerformed
        // TODO add your handling code here:
        Restaurant re = (Restaurant) JComboBox1.getSelectedItem();
        if (re != null){
            populatefoodComboBox(re);
        }    
    }//GEN-LAST:event_JComboBox1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JComboBox1;
    private javax.swing.JComboBox JComboBox2;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnBool;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
